export const CACHE_TAGS = {
  UNIT: "unit",
  UNIT_LIST: "unit-list",
  USER: "user",
  USER_PROFILE: "user-profile",
  USER_STATS: "user-stats",
  USER_UNITS: "user-units",
  USER_LOGS: "user-logs",
  USER_COMMENTS: "user-comments",
  USER_LIKES: "user-likes",
  USER_INTERESTS: "user-interests",
  USER_SKILLS: "user-skills",
  USER_PROVIDERS: "user-providers",
  LOG: "log",
  LOG_LIST: "log-list",
  COMMENT: "comment",
  COMMENT_LIST: "comment-list",
  TAG: "tag",
  TAG_LIST: "tag-list",
  RESOURCE: "resource",
  RESOURCE_LIST: "resource-list",
  DASHBOARD: "dashboard",
} as const;
